# Generated by Django 4.1.7 on 2023-04-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('round_robin', models.IntegerField()),
                ('match_id', models.CharField(max_length=2)),
                ('game', models.IntegerField()),
                ('result', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('opponent', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=3)),
                ('time', models.TimeField()),
                ('player', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('champion', models.CharField(max_length=50)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('kda', models.FloatField()),
                ('cs', models.IntegerField()),
                ('cs_per_min', models.FloatField()),
                ('cs_diff', models.IntegerField()),
                ('dmg', models.IntegerField()),
                ('dmg_percent', models.CharField(max_length=10)),
                ('dmg_per_min', models.FloatField()),
                ('kp_percent', models.CharField(max_length=10)),
                ('gold', models.IntegerField()),
                ('gold_share', models.CharField(max_length=10)),
                ('gold_per_min', models.FloatField()),
                ('dmg_to_gold', models.FloatField()),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('discord_id', models.CharField(max_length=100)),
                ('ign', models.CharField(max_length=100)),
                ('ign2', models.CharField(blank=True, max_length=100, null=True)),
                ('opgg', models.URLField(max_length=255)),
                ('peak_rank', models.CharField(max_length=100)),
                ('primary_role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('group_letter', models.CharField(max_length=1)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='playerdata.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='playerdata.player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='playerdata.player')),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team4', to='playerdata.player')),
                ('player5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team5', to='playerdata.player')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
